In [22]:
import yfinance as yf

In [23]:
df = yf.download("Reliance.NS",start="2022-03-01",end="2026-03-01")
df.columns = df.columns.droplevel(1)

[*********************100%***********************]  1 of 1 completed

In [24]:
df.head()

Price             Close         High          Low         Open    Volume
Date
2022-03-02  1091.369141  1092.483982  1059.814064  1062.202855  21471786
2022-03-03  1082.155151  1098.785820  1078.401303  1092.028893  10186748
2022-03-04  1058.153198  1075.784852  1055.787154  1070.643199  10805667
2022-03-07  1019.022278  1052.033400  1011.036774  1036.835909  17983310
2022-03-08  1017.179382  1021.957085   991.926235  1006.259101  21289374

In [25]:
df.tail()

Price             Close         High          Low         Open    Volume
Date
2026-02-23  1428.000000  1434.900024  1418.300049  1425.000000   7758856
2026-02-24  1428.800049  1433.300049  1415.000000  1425.300049  12529409
2026-02-25  1398.500000  1440.500000  1393.500000  1435.000000  10728792
2026-02-26  1406.800049  1412.900024  1391.900024  1398.500000  16683858
2026-02-27  1393.900024  1410.400024  1388.099976  1398.000000  12031440

In [26]:
return_=(df['Close'].shift(-1)-df['Close'])/df['Close']
df['Target']=(return_>0).astype(int)

In [27]:
print(df['Target'].value_counts())
print(df['Target'].head(10))
print(return_.head(10))

Target
1    505
0    484
Name: count, dtype: int64
Date
2022-03-02    0
2022-03-03    0
2022-03-04    0
2022-03-07    0
2022-03-08    1
2022-03-09    1
2022-03-10    1
2022-03-11    1
2022-03-14    0
2022-03-15    1
Name: Target, dtype: int64
Date
2022-03-02   -0.008443
2022-03-03   -0.022180
2022-03-04   -0.036980
2022-03-07   -0.001808
2022-03-08    0.053053
2022-03-09    0.016206
2022-03-10    0.002884
2022-03-11    0.008211
2022-03-14   -0.022903
2022-03-15    0.016882
Name: Close, dtype: float64

In [28]:
df.dropna(inplace=True)
df.shape

(989, 6)

In [29]:
df['SMA_20'] = df['Close'].rolling(window=20).mean()
df['SMA_50'] = df['Close'].rolling(window=50).mean()

In [30]:
df[['Close','SMA_20','SMA_50']].head(60)

Price             Close       SMA_20       SMA_50
Date
2022-03-02  1091.369141          NaN          NaN
2022-03-03  1082.155151          NaN          NaN
2022-03-04  1058.153198          NaN          NaN
2022-03-07  1019.022278          NaN          NaN
2022-03-08  1017.179382          NaN          NaN
2022-03-09  1071.143799          NaN          NaN
2022-03-10  1088.502441          NaN          NaN
2022-03-11  1091.642090          NaN          NaN
2022-03-14  1100.605835          NaN          NaN
2022-03-15  1075.398193          NaN          NaN
2022-03-16  1093.553223          NaN          NaN
2022-03-17  1129.203369          NaN          NaN
2022-03-21  1122.696777          NaN          NaN
2022-03-22  1151.703735          NaN          NaN
2022-03-23  1155.366577          NaN          NaN
2022-03-24  1173.316650          NaN          NaN
2022-03-25  1181.142944          NaN          NaN
2022-03-28  1193.018921          NaN          NaN
2022-03-29  1193.291748          NaN          NaN
2022-03-30  1216.224609  1115.234503          NaN
2022-03-31  1198.843018  1120.608197          NaN
2022-04-01  1208.443726  1126.922626          NaN
2022-04-04  1212.015625  1134.615747          NaN
2022-04-05  1194.884399  1143.408853          NaN
2022-04-06  1191.699341  1152.134851          NaN
2022-04-07  1170.677856  1157.111554          NaN
2022-04-08  1190.152222  1162.194043          NaN
2022-04-11  1187.672485  1166.995563          NaN
2022-04-12  1165.308594  1170.230701          NaN
2022-04-13  1161.031372  1174.512360          NaN
2022-04-18  1157.482178  1177.708807          NaN
2022-04-19  1201.595703  1181.328424          NaN
2022-04-20  1236.927368  1187.039954          NaN
2022-04-21  1265.889038  1192.749219          NaN
2022-04-22  1255.287109  1197.745245          NaN
2022-04-25  1226.257446  1200.392285          NaN
2022-04-26  1262.954224  1204.482849          NaN
2022-04-27  1264.182617  1208.041034          NaN
2022-04-28  1283.065796  1212.529736          NaN
2022-04-29  1269.597412  1215.198376          NaN
2022-05-02  1265.138062  1218.513129          NaN
2022-05-04  1225.643066  1219.373096          NaN
2022-05-05  1201.641235  1218.854376          NaN
2022-05-06  1192.427246  1218.731519          NaN
2022-05-09  1145.856812  1216.439392          NaN
2022-05-10  1125.995483  1214.205273          NaN
2022-05-11  1114.460938  1210.420709          NaN
2022-05-12  1091.755859  1205.624878          NaN
2022-05-13  1104.132202  1202.566058          NaN
2022-05-16  1104.405151  1199.734747  1163.602273
2022-05-17  1150.793701  1199.400323  1164.790764
2022-05-18  1154.979736  1197.069525  1166.247256
2022-05-19  1128.361450  1191.641229  1167.651421
2022-05-20  1194.156372  1188.054596  1171.154103
2022-05-23  1186.171021  1184.598792  1174.533936
2022-05-24  1190.243286  1182.798083  1176.915925
2022-05-25  1188.491455  1179.074945  1178.915706
2022-05-26  1177.161621  1174.723895  1180.626096
2022-05-27  1171.701416  1169.155676  1182.048008
2022-05-30  1212.516113  1166.301611  1184.790366

In [31]:
daily_change=df['Close'].diff()
gain=daily_change.clip(lower=0)
loss=daily_change.clip(upper=0).abs()
avg_gain=gain.rolling(14).mean()
avg_loss=loss.rolling(14).mean()
RS=avg_gain/avg_loss
df['RSI']=100-100/(1+RS)

In [32]:
df.head(60)

Price,Close,High,Low,Open,Volume,Target,SMA_20,SMA_50,RSI
Date,,,,,,,,,
2022-03-02,1091.369141,1092.483982,1059.814064,1062.202855,21471786,0,NaN,NaN,NaN
2022-03-03,1082.155151,1098.785820,1078.401303,1092.028893,10186748,0,NaN,NaN,NaN
2022-03-04,1058.153198,1075.784852,1055.787154,1070.643199,10805667,0,NaN,NaN,NaN
2022-03-07,1019.022278,1052.033400,1011.036774,1036.835909,17983310,0,NaN,NaN,NaN
2022-03-08,1017.179382,1021.957085,991.926235,1006.259101,21289374,1,NaN,NaN,NaN
2022-03-09,1071.143799,1077.013475,1016.565078,1017.406956,20414228,1,NaN,NaN,NaN
2022-03-10,1088.502441,1094.303876,1073.828372,1092.028820,17980493,1,NaN,NaN,NaN
2022-03-11,1091.642090,1097.034080,1081.131313,1081.131313,12257423,1,NaN,NaN,NaN
2022-03-14,1100.605835,1103.131228,1080.198570,1086.068246,8340678,0,NaN,NaN,NaN
2022-03-15,1075.398193,1104.746453,1065.114887,1104.746453,15925769,1,NaN,NaN,NaN
2022-03-16,1093.553223,1095.623556,1081.609147,1083.838710,11149828,1,NaN,NaN,NaN
2022-03-17,1129.203369,1136.346995,1098.899497,1106.930494,21422098,0,NaN,NaN,NaN
2022-03-21,1122.696777,1130.249969,1109.774462,1112.049519,11999466,1,NaN,NaN,NaN
2022-03-22,1151.703735,1153.432744,1116.417559,1119.375023,22557065,1,NaN,NaN,NaN
2022-03-23,1155.366577,1167.037689,1147.995481,1147.995481,15462187,1,NaN,NaN,61.601918
2022-03-24,1173.316650,1175.819296,1142.080154,1142.080154,13168266,1,NaN,NaN,66.019016
2022-03-25,1181.142944,1190.311409,1172.565900,1175.068546,14222488,1,NaN,NaN,72.914568
2022-03-28,1193.018921,1196.567927,1176.888684,1187.581436,9891424,1,NaN,NaN,86.082285
2022-03-29,1193.291748,1200.321639,1186.398339,1200.321639,8684065,1,NaN,NaN,86.760406
2022-03-30,1216.224609,1223.072526,1190.812170,1201.186466,15811550,0,1115.234503,NaN,84.790013
2022-03-31,1198.843018,1214.745786,1196.044781,1212.584464,13223718,1,1120.608197,NaN,76.456481
2022-04-01,1208.443726,1212.675381,1193.041632,1199.411741,7922880,1,1126.922626,NaN,77.164019
2022-04-04,1212.015625,1217.157279,1201.982654,1208.261776,7929162,0,1134.615747,NaN,76.576580
2022-04-05,1194.884399,1214.836726,1192.450114,1206.282428,13149870,0,1143.408853,NaN,79.645501
2022-04-06,1191.699341,1198.729232,1177.161752,1177.161752,12257215,0,1152.134851,NaN,76.304867
2022-04-07,1170.677856,1185.761494,1168.015981,1180.801815,15496499,1,1157.111554,NaN,62.061699
2022-04-08,1190.152222,1194.406624,1164.830774,1164.830774,15152495,0,1162.194043,NaN,68.241637
2022-04-11,1187.672485,1200.572053,1175.296098,1183.031265,9254209,0,1166.995563,NaN,61.356142
2022-04-12,1165.308594,1184.214319,1162.737707,1177.116066,13217742,0,1170.230701,NaN,52.807401
2022-04-13,1161.031372,1179.664132,1158.233016,1171.428413,10354235,0,1174.512360,NaN,46.240623
2022-04-18,1157.482178,1164.739658,1147.449209,1152.545368,9974224,1,1177.708807,NaN,42.565027
2022-04-19,1201.595703,1213.972090,1160.758429,1163.920737,26141820,1,1181.328424,NaN,52.241059
2022-04-20,1236.927368,1244.002873,1205.372294,1209.012408,25072240,1,1187.039954,NaN,59.636228
2022-04-21,1265.889038,1269.028599,1243.092862,1251.692654,21708633,0,1192.749219,NaN,60.683130
2022-04-22,1255.287109,1274.943602,1248.643917,1255.332603,15054154,0,1197.745245,NaN,62.506248
2022-04-25,1226.257446,1255.105154,1211.992821,1247.825046,17063215,1,1200.392285,NaN,53.634081
2022-04-26,1262.954224,1271.758738,1232.036181,1233.082661,12227666,1,1204.482849,NaN,59.154459
2022-04-27,1264.182617,1286.773948,1253.580734,1253.944805,19338945,1,1208.041034,NaN,63.208991
2022-04-28,1283.065796,1297.239434,1267.709076,1278.561177,25614076,0,1212.529736,NaN,66.432065
2022-04-29,1269.597412,1299.582709,1263.704989,1299.582709,18214862,0,1215.198376,NaN,68.287308
2022-05-02,1265.138062,1276.536088,1254.945744,1256.743114,9467006,0,1218.513129,NaN,64.677516
2022-05-04,1225.643066,1269.483539,1217.748671,1267.208483,19247660,0,1219.373096,NaN,56.491589
2022-05-05,1201.641235,1242.182800,1197.591676,1239.225215,17210669,0,1218.854376,NaN,56.176966
2022-05-06,1192.427246,1209.876925,1180.096353,1188.582410,19649948,0,1218.731519,NaN,55.249540
2022-05-09,1145.856812,1181.711783,1140.715158,1171.633199,18083752,0,1216.439392,NaN,48.300662
2022-05-10,1125.995483,1149.633417,1118.419545,1135.255057,19511677,0,1214.205273,NaN,38.105827
2022-05-11,1114.460938,1130.682161,1102.016310,1125.085448,16643899,0,1210.420709,NaN,29.172834
2022-05-12,1091.755859,1107.885974,1078.378487,1104.541691,20490321,1,1205.624878,NaN,19.742267
2022-05-13,1104.132202,1127.519799,1099.013296,1103.859239,19308778,1,1202.566058,NaN,23.895989
2022-05-16,1104.405151,1128.884719,1099.604703,1107.703940,13437911,1,1199.734747,1163.602273,26.635843
2022-05-17,1150.793701,1155.685138,1106.589272,1107.999824,16551828,1,1199.400323,1164.790764,29.264810
2022-05-18,1154.979736,1169.380842,1141.283906,1155.571277,17276788,0,1197.069525,1166.247256,30.029975
2022-05-19,1128.361450,1143.217615,1122.082329,1130.249808,14699118,1,1191.641229,1167.651421,22.487428
2022-05-20,1194.156372,1203.233850,1138.440180,1143.217762,21793091,0,1188.054596,1171.154103,38.688775
2022-05-23,1186.171021,1207.397297,1179.846284,1197.364206,15252755,1,1184.598792,1174.533936,38.283983
2022-05-24,1190.243286,1200.321750,1181.984819,1186.216474,13527818,0,1182.798083,1176.915925,44.130984
2022-05-25,1188.491455,1208.830478,1183.713753,1198.956737,12714544,0,1179.074945,1178.915706,47.646209
2022-05-26,1177.161621,1198.911195,1159.370618,1194.133493,17882023,0,1174.723895,1180.626096,47.288018
2022-05-27,1171.701416,1185.374499,1155.776024,1179.868895,16521973,1,1169.155676,1182.048008,55.376731
2022-05-30,1212.516113,1216.702154,1180.392243,1189.856419,13853398,0,1166.301611,1184.790366,66.556381

In [33]:
print(df['RSI'].describe())
print(df['RSI'].head(20))

count    975.000000
mean      51.485630
std       17.083185
min        7.722604
25%       38.741114
50%       52.553386
75%       64.495286
max       97.563393
Name: RSI, dtype: float64
Date
2022-03-02          NaN
2022-03-03          NaN
2022-03-04          NaN
2022-03-07          NaN
2022-03-08          NaN
2022-03-09          NaN
2022-03-10          NaN
2022-03-11          NaN
2022-03-14          NaN
2022-03-15          NaN
2022-03-16          NaN
2022-03-17          NaN
2022-03-21          NaN
2022-03-22          NaN
2022-03-23    61.601918
2022-03-24    66.019016
2022-03-25    72.914568
2022-03-28    86.082285
2022-03-29    86.760406
2022-03-30    84.790013
Name: RSI, dtype: float64

In [34]:
ema_12 = df['Close'].ewm(span=12).mean()
ema_26 = df['Close'].ewm(span=26).mean()

df['MACD'] = ema_12 - ema_26
df['Signal_Line'] = df['MACD'].ewm(span=9).mean()
df['MACD_Histogram'] = df['MACD']-df['Signal_Line']

In [35]:
df[['MACD', 'Signal_Line', 'MACD_Histogram']].head(30)

Price            MACD  Signal_Line  MACD_Histogram
Date
2022-03-02   0.000000     0.000000        0.000000
2022-03-03  -0.206724    -0.114847       -0.091877
2022-03-04  -1.007707    -0.480773       -0.526934
2022-03-07  -2.760120    -1.252909       -1.507210
2022-03-08  -3.727581    -1.989068       -1.738512
2022-03-09  -1.931540    -1.973475        0.041935
2022-03-10   0.039925    -1.463937        1.503862
2022-03-11   1.510532    -0.749116        2.259648
2022-03-14   2.950640     0.105546        2.845094
2022-03-15   2.630856     0.671362        1.959494
2022-03-16   3.330099     1.253078        2.077021
2022-03-17   5.755741     2.220062        3.535680
2022-03-21   7.110765     3.255104        3.855661
2022-03-22   9.713796     4.606267        5.107529
2022-03-23  11.770293     6.091323        5.678970
2022-03-24  14.271477     7.774738        6.496739
2022-03-25  16.486197     9.557166        6.929030
2022-03-28  18.728705    11.425124        7.303580
2022-03-29  20.241794    13.214242        7.027552
2022-03-30  22.658604    15.125146        7.533458
2022-03-31  23.104370    16.735847        6.368524
2022-04-01  23.818170    18.162841        5.655329
2022-04-04  24.332055    19.404010        4.928045
2022-04-05  23.266263    20.180126        3.086137
2022-04-06  21.942515    20.533940        1.408574
2022-04-07  19.178839    20.262098       -1.083259
2022-04-08  18.181821    19.845035       -1.663213
2022-04-11  17.015187    19.277968       -2.262781
2022-04-12  14.294929    18.279816       -3.984887
2022-04-13  11.694760    16.961172       -5.266412

In [36]:
print(df.columns)
print(df.head(2))

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'Target', 'SMA_20', 'SMA_50',
       'RSI', 'MACD', 'Signal_Line', 'MACD_Histogram'],
      dtype='str', name='Price')
Price             Close         High          Low         Open    Volume  \
Date
2022-03-02  1091.369141  1092.483982  1059.814064  1062.202855  21471786
2022-03-03  1082.155151  1098.785820  1078.401303  1092.028893  10186748

Price       Target  SMA_20  SMA_50  RSI      MACD  Signal_Line  MACD_Histogram
Date
2022-03-02       0     NaN     NaN  NaN  0.000000     0.000000        0.000000
2022-03-03       0     NaN     NaN  NaN -0.206724    -0.114847       -0.091877

In [37]:
std_20=df['Close'].rolling(20).std()
df['bb_Upper']=df['SMA_20']+2*std_20
df['bb_Lower']=df['SMA_20']-2*std_20
df['bb_Width']=(df['bb_Upper']-df['bb_Lower'])/df['SMA_20']

In [41]:
df['Momentum']=df['Close']-df['Close'].shift(10)
df['Volatility']=return_.rolling(20).std

In [44]:
df.dropna(inplace=True)
print(df.shape)

(940, 17)